services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongo_mydb:/data/db
    command: mongod --quiet --logpath /dev/null

  redis:
    image: redis:7
    ports:
      - 6379:6379

volumes:
  mongo_mydb:
